### ISSUE TITLE
pgp encrypted aren't sending

### ISSUE THREAD

**Issue by lgwapnitsky** [anonaddy/anonaddy#146]
i created a gpg key for my server, and then added my personal public key to my account. WHen enabled, no messages get via the alias.

**Comment by lgwapnitsky** [comment]
Issues noticed while watching the logs and rspamd:

* rspamd doesn't see the envelope for the messages
* postfix never sends out the message like it does with unencrypted messages. It receives, but nothing else.

**Comment by willbrowningme** [comment]
Could you check the Laravel log in `/var/www/anonaddy/storage/logs`?

**Comment by lgwapnitsky** [comment]
Nothing is showing

```
[2021-05-02 09:07:22] production.ERROR: Command "cache:config" is not defined.                                                                                          Did you mean one of these?                                  cache:clear                                             cache:forget                                            cache:table {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"cache:config\" is not defined.                                                                     Did you mean one of these?                                  cache:clear                                             cache:forget                                            cache:table at /var/www/anonaddy/vendor/symfony/console/Application.php:675)                                [stacktrace]                                            #0 /var/www/anonaddy/vendor/symfony/console/Application.php(254): Symfony\\Component\\Console\\Application->find()                                                      #1 /var/www/anonaddy/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()                                                     #2 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()                               #3 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()                                #4 /var/www/anonaddy/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()                             #5 {main}                                               "}
```

**Comment by lgwapnitsky** [comment]
Sent you a copy of today's logs. with debug on, nothing is reporting.  System has no laravel.log file.

**Comment by lgwapnitsky** [comment]
Also noticing (using redis-commander) that encrypted emails stay in the redis queue under anonaddy_cache instead of being processed. I had 25 in there and just deleted it. Sent a new email with encryption on, and the cache is recreated with one message sitting in there. 

I turned off encryption, the message went straight through.

Could this be a php 8 issue? I'm considering rebuilding the box with 7.4 just to test

**Comment by lgwapnitsky** [comment]
tried a second box with 7.4, fresh install. Moved my IPs over, changed DKIMs. Same issue with encrypted messages. No errors in logs

**Comment by lgwapnitsky** [comment]
```
[2021-05-02 19:08:59] production.ERROR: read error on connection to 127.0.0.1:6379 {"exception":"[object] (RedisException(code: 0): read error on connection to 127\
.0.0.1:6379 at /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:116)
[stacktrace]
#0 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Redis->blPop()
#1 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(532): Illuminate\\Redis\\Connections\\Connection->command()
#2 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(174): Illuminate\\Redis\\Connections\\PhpRedisConnection->com\
mand()
#3 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(272): Illuminate\\Redis\\Connections\\PhpRedisConnection->blpop()
#4 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(212): Illuminate\\Queue\\RedisQueue->retrieveNextJob()
#5 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\\Queue\\RedisQueue->pop()
#6 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(336): Illuminate\\Queue\\Worker->Illuminate\\Queue\\{closure}()
#7 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(145): Illuminate\\Queue\\Worker->getNextJob()
#8 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon()
#9 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#10 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#11 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#13 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#14 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\\Container\\BoundMethod::call()
#15 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#16 /var/www/anonaddy/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#17 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#18 /var/www/anonaddy/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#19 /var/www/anonaddy/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#20 /var/www/anonaddy/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#21 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#22 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#23 /var/www/anonaddy/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#24 {main}
"}
```

**Comment by lgwapnitsky** [comment]
```
May  2 18:24:55 anonaddy postfix/postscreen[7203]: CONNECT from [209.85.217.45]:35770 to [71.185.204.33]:25
May  2 18:25:01 anonaddy postfix/postscreen[7203]: PASS NEW [209.85.217.45]:35770
May  2 18:25:02 anonaddy postfix/smtpd[7207]: connect from mail-vs1-f45.google.com[209.85.217.45]
May  2 18:25:03 anonaddy postfix/smtpd[7207]: Anonymous TLS connection established from mail-vs1-f45.google.com[209.85.217.45]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange ECDHE (P-384) server-signature RSA-PSS (2048 bits) server-digest SHA256
May  2 18:25:10 anonaddy postfix/smtpd[7207]: 5C3338206C: client=mail-vs1-f45.google.com[209.85.217.45]
May  2 18:25:10 anonaddy postfix/cleanup[7216]: 5C3338206C: message-id=<CAMbq2J9i9ePhmADm9urEjs7_KMXdPud+sqGMk2tHskS-cppAww@mail.gmail.com>
May  2 18:25:11 anonaddy postfix/qmgr[3668]: 5C3338206C: from=<larry@blingblingbling.com>, size=3984, nrcpt=1 (queue active)
May  2 18:25:11 anonaddy postfix/smtpd[7207]: disconnect from mail-vs1-f45.google.com[209.85.217.45] ehlo=2 starttls=1 mail=1 rcpt=1 bdat=1 quit=1 commands=7
May  2 18:25:12 anonaddy postfix/pipe[7217]: 5C3338206C: to=<test@lgwapnitsky.anon.qual-itsystems.com>, relay=anonaddy, delay=9.3, delays=8.8/0.01/0/0.49, dsn=2.0.0, status=sent (delivered via anonaddy service ( In StreamHandler.php line 111:                                                                     ))
May  2 18:25:12 anonaddy postfix/qmgr[3668]: 5C3338206C: removed
```

this is from mail.log on a failed message sent when gpg is enabled on the recipient. I've replaced my personal domain with blingblingbling.

**Comment by lgwapnitsky** [comment]
REsolved. It was a fat-finger copy/paste error. Thanks for all the help!
