### ISSUE TITLE
encrypted emails not forwarding

### ISSUE THREAD

**Issue by Mr-Sheep** [anonaddy/anonaddy#294]
After pasting my PGP public key in the recipients tab, I tried to send a few test emails, but non arrived. A fail delivery pops up with the error code: `An error has occurred, please check the logs. `

`/var/log/mail.log`: 

```
Jun  3 09:58:41 mail postfix/smtpd[25438]: connect from mail-4316.protonmail.ch[185.70.43.16]
Jun  3 09:58:41 mail postfix/smtpd[25438]: Anonymous TLS connection established from mail-4316.protonmail.ch[185.70.43.16]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange ECDHE (P-384) server-signature RSA-PSS (2048 bits) server-digest SHA256
Jun  3 09:58:42 mail postfix/smtpd[25438]: 69CFC5FEC4: client=mail-4316.protonmail.ch[185.70.43.16]
Jun  3 09:58:42 mail postfix/cleanup[25442]: 69CFC5FEC4: message-id=<uuid@protonmail.com>
Jun  3 09:58:42 mail postfix/qmgr[8987]: 69CFC5FEC4: from=<user@protonmail.com>, size=1348, nrcpt=1 (queue active)
Jun  3 09:58:42 mail postfix/smtpd[25438]: disconnect from mail-4316.protonmail.ch[185.70.43.16] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Jun  3 09:58:43 mail postfix/smtpd[25438]: connect from localhost[::1]
Jun  3 09:58:43 mail postfix/pipe[25443]: 69CFC5FEC4: to=<user@example.email>, relay=anonaddy, delay=1.4, delays=0.99/0.02/0/0.43, dsn=2.0.0, status=sent (delivered via anonaddy service)
Jun  3 09:58:43 mail postfix/qmgr[8987]: 69CFC5FEC4: removed
Jun  3 10:00:13 mail postfix/smtpd[25438]: lost connection after CONNECT from localhost[::1]
Jun  3 10:00:13 mail postfix/smtpd[25438]: disconnect from localhost[::1] commands=0/0
Jun  3 10:00:15 mail postfix/smtpd[25438]: connect from localhost[::1]
Jun  3 10:01:45 mail postfix/smtpd[25537]: connect from localhost[::1]
Jun  3 10:01:45 mail postfix/smtpd[25438]: lost connection after CONNECT from localhost[::1]
Jun  3 10:01:45 mail postfix/smtpd[25438]: disconnect from localhost[::1] commands=0/0
Jun  3 10:03:15 mail postfix/smtpd[25537]: lost connection after CONNECT from localhost[::1]
Jun  3 10:03:15 mail postfix/smtpd[25537]: disconnect from localhost[::1] commands=0/0
Jun  3 10:03:16 mail postfix/smtpd[25438]: connect from localhost[::1]
Jun  3 10:03:16 mail postfix/smtpd[25438]: 537115FEC4: client=localhost[::1]
Jun  3 10:03:46 mail postfix/smtpd[25438]: lost connection after DATA (0 bytes) from localhost[::1]
Jun  3 10:03:46 mail postfix/smtpd[25438]: disconnect from localhost[::1] ehlo=1 mail=1 rcpt=1 data=0/1 commands=3/4
Jun  3 10:03:46 mail postfix/smtpd[25537]: connect from localhost[::1]
Jun  3 10:03:46 mail postfix/smtpd[25537]: 8A6B25FEC4: client=localhost[::1]
Jun  3 10:04:16 mail postfix/smtpd[25537]: lost connection after DATA (0 bytes) from localhost[::1]
Jun  3 10:04:16 mail postfix/smtpd[25537]: disconnect from localhost[::1] ehlo=1 mail=1 rcpt=1 data=0/1 commands=3/4
Jun  3 10:04:16 mail postfix/smtpd[25438]: connect from localhost[::1]
Jun  3 10:04:16 mail postfix/smtpd[25438]: CB77F5FEC4: client=localhost[::1]
Jun  3 10:04:46 mail postfix/smtpd[25438]: lost connection after DATA (0 bytes) from localhost[::1]
Jun  3 10:04:46 mail postfix/smtpd[25438]: disconnect from localhost[::1] ehlo=1 mail=1 rcpt=1 data=0/1 commands=3/4
Jun  3 10:08:07 mail postfix/anvil[25439]: statistics: max connection rate 1/60s for (smtp:185.70.43.16) at Jun  3 09:58:41
Jun  3 10:08:07 mail postfix/anvil[25439]: statistics: max connection count 1 for (smtp:185.70.43.16) at Jun  3 09:58:41
Jun  3 10:08:07 mail postfix/anvil[25439]: statistics: max cache size 1 at Jun  3 09:58:41
```

`php -i | grep gnupg`:
```
/etc/php/8.0/cli/conf.d/20-gnupg.ini,
gnupg
gnupg support => enabled
```

nothing pops up in `/var/www/anonaddy/storage/logs/laravel-2022-06-03.log`

**Comment by willbrowningme** [comment]
Hmm, are you sure there is nothing in the laravel logs? There definitely should be if it is saying there is a failed delivery.

**Comment by Mr-Sheep** [comment]
apologies, I did not see the error message in the `laravel.log` file. the problem seems to be that anonaddy can't find the correct key to sign for the email; however, I did import the public key for johndoe@protonmail.com under the recipient tab. 
(actual email address redacted for privacy reasons :))
```
[2022-06-20 08:25:53] production.ERROR: Unable to find an active key to sign for ojgm88gk+johndoe=protonmail.com@example.com,try importing keys first {"exception":"[object] (Swift_SwiftException(code: 0): Unable to find an active key to sign for ojgm88gk+johndoe=protonmail.com@example.com,try importing keys first at /var/www/anonaddy/app/Helpers/OpenPGPSigner.php:426)
[stacktrace]
#0 /var/www/anonaddy/app/Helpers/OpenPGPSigner.php(197): App\\Helpers\\OpenPGPSigner->getKey()
#1 /var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Message.php(189): App\\Helpers\\OpenPGPSigner->signMessage()
#2 /var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Message.php(169): Swift_Message->doSign()
#3 /var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(400): Swift_Message->toByteStream()
#4 /var/www/anonaddy/app/CustomMailDriver/CustomSmtpTransport.php(188): Swift_Transport_AbstractSmtpTransport->streamMessage()
#5 /var/www/anonaddy/app/CustomMailDriver/CustomSmtpTransport.php(143): App\\CustomMailDriver\\CustomSmtpTransport->doMailTransaction()
#6 /var/www/anonaddy/app/CustomMailDriver/CustomSmtpTransport.php(101): App\\CustomMailDriver\\CustomSmtpTransport->sendTo()
#7 /var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): App\\CustomMailDriver\\CustomSmtpTransport->send()
#8 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(521): Swift_Mailer->send()
#9 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(288): Illuminate\\Mail\\Mailer->sendSwiftMessage()
#10 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(187): Illuminate\\Mail\\Mailer->send()
#11 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}()
#12 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(188): Illuminate\\Mail\\Mailable->withLocale()
#13 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Mail/SendQueuedMailable.php(65): Illuminate\\Mail\\Mailable->send()
#14 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Mail\\SendQueuedMailable->handle()
#15 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#17 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#18 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#19 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#20 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#21 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#23 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow()
#24 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#25 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
#27 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#28 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#29 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\\Queue\\Jobs\\Job->fire()
#30 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\\Queue\\Worker->process()
#31 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\\Queue\\Worker->runJob()
#32 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon()
#33 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#34 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#35 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#36 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#37 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#38 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#39 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#40 /var/www/anonaddy/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#41 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#42 /var/www/anonaddy/vendor/symfony/console/Application.php(1015): Illuminate\\Console\\Command->run()
#43 /var/www/anonaddy/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#44 /var/www/anonaddy/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#45 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#46 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#47 /var/www/anonaddy/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#48 {main}
"}
```

**Comment by willbrowningme** [comment]
That error is actually referring to the private signing key that is missing on the server. The one that signs encrypted messages, and that you set in your `.env` file under `ANONADDY_SIGNING_KEY_FINGERPRINT`.

Please see the section "Adding your private key to sign emails" near the bottom of the [self-hosting instructions](https://anonaddy.com/self-hosting/).

**Comment by Mr-Sheep** [comment]
I re-generated another gpg key using this command: 
```
gpg --batch --gen-key <<EOF
%no-protection
Key-Type:1
Key-Length:4096
Subkey-Type:1
Subkey-Length:4096
Name-Real: Mailer
Name-Email: mailer@example.com
Expire-Date:0
EOF
```
and replaced the value for `ANONADDY_SIGNING_KEY_FINGERPRINT= `, the error messgae now becomes 
```
[2022-06-20 08:51:54] production.ERROR: get_key failed {"exception":"[object] (Exception(code: 0): get_key failed at /var/www/anonaddy/app/Helpers/OpenPGPSigner.php:354)
[stacktrace]
```

**Comment by willbrowningme** [comment]
Did you make sure to generate the private key as the user that the web application is running as?

e.g. if your web application is run by user janedoe make sure you generate the key for that user and not some other sudo user e.g. johndoe.

**Comment by Mr-Sheep** [comment]
> Did you make sure to generate the private key as the user that the web application is running as?

that's it xD, thx for helping!
maybe consider adding a bold text in the https://github.com/anonaddy/anonaddy/blob/master/SELF-HOSTING.md?
