### ISSUE TITLE
Update problem to release v0.13.9

### ISSUE THREAD

**Issue by markus-gitdev** [anonaddy/anonaddy#347]
When trying to update to release [v0.13.9](https://github.com/anonaddy/anonaddy/releases/tag/v0.13.9) I get the following error, when executing `npm run production`:

````
> production
> mix --production

[webpack-cli] /var/www/anonaddy/node_modules/postcss-import/index.js:45
      if (styles.source?.input?.file) {
                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/www/anonaddy/webpack.mix.js:8:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
````

Before the update attempt, I was running release [v0.13.7](https://github.com/anonaddy/anonaddy/releases/tag/v0.13.7). I followed the [instructions on how to update](https://anonaddy.com/self-hosting/) and also checked for breaking changes (which there aren't any described between these two releases).

Can someone help me with this issue?

Thank you and best regards!

**Comment by willbrowningme** [comment]
Did you make sure to run npm install beforehand?

What node and npm versions are you running?

**Comment by markus-gitdev** [comment]
Yes, I did that. I also ran it again and didn't realized the warnings before:

````
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'husky@8.0.1',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'lint-staged@13.0.3',
npm WARN EBADENGINE   required: { node: '^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'yaml@2.1.3',
npm WARN EBADENGINE   required: { node: '>= 14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'postcss-import@15.0.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

> prepare
> husky install

husky - Git hooks installed

up to date, audited 848 packages in 3s

106 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
````

Maybe these warnings are the problem?

**Comment by willbrowningme** [comment]
You need to update your node version to at least 14. If you are using node version manager please run:

`nvm ls-remote` and then find a newer version and install it by running `nvm install vx.x.x` then run `nvm use vx.x.x`.

**Comment by markus-gitdev** [comment]
Yep, that was the problem. Thank you for the quick replies!
