### ISSUE TITLE
Publik key in GUI cant be removed

### ISSUE THREAD

**Issue by daggr8** [anonaddy/anonaddy#71]
Got the self hosted version up and running. Everything is working except the GPG encryption. 
First i tried adding my ProtonMail public key to the recipient in the GUI, that didn't work so i followed the guide in the instructions.
I've generated new keys but when i try to delete the old public key from my default recipient in the GUI i get an error message saying.
```
Error
{ "message": "Server Error" }
```
I've added the new fingerprint to ANONADDY_SIGNING_KEY_FINGERPRINT in the .env file.

I think i have to add the public key in the GUI on the recipient as well? And then use the private key in ProtonMail to decrypt the messages.

So Q1, the keys should be generated for the e-mail address i use in .env (MAIL_FROM_ADDRESS) correct?
Q2, The recipient in the GUI is not the same e-mail address as (MAIL_FROM_ADDRESS) ofc. But that shouldn't matter?
Q3, How can i remove the public key from the GUI and add the newly generated public key? 

Thanks :)

**Comment by willbrowningme** [comment]
For the `ANONADDY_SIGNING_KEY_FINGERPRINT`this needs to be a private key that exists on the mail server where you are hosting the application. That way it can be used to sign forwarded emails that are encrypted.

A1: Yes you can generate a key pair on the server for the `MAIL_FROM_ADDRESS` and enter the fingerprint of this for the signing key variable above.

A2: The recipient will not be the same because that is the destination where email will be forwarded. This should be a real email address such as a Protonmail one, you can then add your Protonmail public key to the recipient.

A3: I'm not sure why you are getting the "Server Error" message but you can check the Laravel log file in `storage/logs` to see what it says. In order to remove it you can simply delete the data in the database for that recipient in the `fingerprint` column and change the `should_encrypt` column to 0.

**Comment by daggr8** [comment]
Ah i see! Thank you!I've generated new GPG keys. Is there a way to see if that works? 

The Laravel log says
```

`[2020-08-30 11:54:16] production.ERROR: Class 'gnupg' not found {"exception":"[object] (Error(code: 0): Class 'gnupg' not found at /var/www/anonaddy/app/Http/Controllers/Api/RecipientKeyController.php:15)
[stacktrace]
#0 [internal function]: App\\Http\\Controllers\\Api\\RecipientKeyController->__construct()
#1 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): ReflectionClass->newInstanceArgs()
#2 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build()
#3 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()
#4 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve()
#5 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make()
#6 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Route.php(253): Illuminate\\Foundation\\Application->make()
#7 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Route.php(970): Illuminate\\Routing\\Route->getController()
#8 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Route.php(931): Illuminate\\Routing\\Route->controllerMiddleware()
#9 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\\Routing\\Route->gatherMiddleware()
#10 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(678): Illuminate\\Routing\\Router->gatherRouteMiddleware()
#11 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#12 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#13 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#14 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#15 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#16 /var/www/anonaddy/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#18 /var/www/anonaddy/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#20 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#22 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#24 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#26 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#28 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#30 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#31 /var/www/anonaddy/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#32 {main}
"} `
```
I managed to delete the fingerprint in the database. But when i try to add the public key i get the same error.
```
[2020-08-30 12:10:22] production.ERROR: Class 'gnupg' not found {"exception":"[object] (Error(code: 0): Class 'gnupg' not found at /var/www/anonaddy/app/Http/Controllers/Api/RecipientKeyController.php:15)
[stacktrace]
#0 [internal function]: App\\Http\\Controllers\\Api\\RecipientKeyController->__construct()
#1 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): ReflectionClass->newInstanceArgs()
#2 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build()
#3 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()
#4 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve()
#5 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make()
#6 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Route.php(253): Illuminate\\Foundation\\Application->make()
#7 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Route.php(970): Illuminate\\Routing\\Route->getController()
#8 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Route.php(931): Illuminate\\Routing\\Route->controllerMiddleware()
#9 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\\Routing\\Route->gatherMiddleware()
#10 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(678): Illuminate\\Routing\\Router->gatherRouteMiddleware()
#11 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#12 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#13 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#14 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#15 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#16 /var/www/anonaddy/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#18 /var/www/anonaddy/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#20 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#22 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#24 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#26 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#28 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#30 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#31 /var/www/anonaddy/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#32 {main}
"} 
```

**Comment by willbrowningme** [comment]
I'm not sure what is causing the "No recipient addresses found in message header" error, does it still show this if you toggle encryption off for the recipient?

**Comment by daggr8** [comment]
Nope :).

**Comment by willbrowningme** [comment]
Are you sure that the `ANONADDY_SIGNING_KEY_FINGERPRINT` In your `.env` file is correct? It should be in this format:

`26A987650243B28802524E2F809FD0D502E2F695`

**Comment by daggr8** [comment]
Yepp. But i get the same error if i remove the last digit. Just for test. Hmm.

**Comment by willbrowningme** [comment]
I think that error is caused because you have a password on your secret key. Apparantly the GnuPG module in PHP doesn't support decrypting keys with passwords at the moment.

Please try removing the passphrase by doing `gpg --edit-key <keyid>` and leaving the it blank.

**Comment by daggr8** [comment]
Same issue. Get a mail saying the the key expired. Just to clarify.
I should use the ID i see when running 'gpg --list-keys' in the 'ANONADDY_SIGNING_KEY_FINGERPRINT' correct?

**Comment by daggr8** [comment]
Aah. In the Laravel-log i see `[2020-08-30 14:53:07] production.INFO: PHPMailerPGP requires the GnuPG class`

**Comment by daggr8** [comment]
Huh. A reboot seems to have solved it. I guess it's a combination of gpg, gnupg1 issues.

**Comment by willbrowningme** [comment]
Is it now working as expected?

**Comment by daggr8** [comment]
I think so. Thank you! :)
